services:
  app:
    container_name: app
    platform: linux/amd64
    image: appscenter/larasuperdock:latest
    working_dir: /www/
    volumes:
      - ./:/www
      - redis:/var/lib/redis
    ports:
      - "80:80"
    depends_on:
      - postgres
      - rabbitmq
    restart: on-failure
    tty: true
    stdin_open: true
    networks:
      - network

  postgres:
    container_name: postgres
    image: postgres:18.1-bookworm
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "database" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    ports:
      - "5432:5432"
    networks:
      - network

  postgres-test:
    container_name: postgres-test
    image: postgres:18.1-bookworm
    volumes:
      - ./:/www
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "database" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    ports:
      - "5433:5432"
    networks:
      - network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  network:
    driver: bridge

volumes:
  redis:
